//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Models.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password do not match..
        /// </summary>
        public static string ChangePassword_Compare {
            get {
                return ResourceManager.GetString("ChangePassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ChangePassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid e-mail address..
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOn_Password {
            get {
                return ResourceManager.GetString("LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string LogOn_RememberMe {
            get {
                return ResourceManager.GetString("LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LogOn_Username {
            get {
                return ResourceManager.GetString("LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password do not match..
        /// </summary>
        public static string Register_Compare {
            get {
                return ResourceManager.GetString("Register_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_ConfirmPassword {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string Register_EmailAddress {
            get {
                return ResourceManager.GetString("Register_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Register_Pin {
            get {
                return ResourceManager.GetString("Register_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Register_Username {
            get {
                return ResourceManager.GetString("Register_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Address.
        /// </summary>
        public static string Reset_EmailAddress {
            get {
                return ResourceManager.GetString("Reset_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Reset_Username {
            get {
                return ResourceManager.GetString("Reset_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm password do not match..
        /// </summary>
        public static string ResetCompletion_Compare {
            get {
                return ResourceManager.GetString("ResetCompletion_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ResetCompletion_ConfirmPassword {
            get {
                return ResourceManager.GetString("ResetCompletion_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string ResetCompletion_Password {
            get {
                return ResourceManager.GetString("ResetCompletion_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string ResetCompletion_Username {
            get {
                return ResourceManager.GetString("ResetCompletion_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a valid region..
        /// </summary>
        public static string ValidRegion {
            get {
                return ResourceManager.GetString("ValidRegion", resourceCulture);
            }
        }
    }
}
