//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Purchase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Purchase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Models.Purchase", typeof(Purchase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Device.
        /// </summary>
        public static string Add_Device {
            get {
                return ResourceManager.GetString("Add_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Quantity.
        /// </summary>
        public static string Add_Quantity {
            get {
                return ResourceManager.GetString("Add_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a quantity between {1} and {2}..
        /// </summary>
        public static string Add_QuantityError {
            get {
                return ResourceManager.GetString("Add_QuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Rate.
        /// </summary>
        public static string Add_Rate {
            get {
                return ResourceManager.GetString("Add_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string AddCard_Address {
            get {
                return ResourceManager.GetString("AddCard_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string AddCard_CardNumber {
            get {
                return ResourceManager.GetString("AddCard_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string AddCard_City {
            get {
                return ResourceManager.GetString("AddCard_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string AddCard_Country {
            get {
                return ResourceManager.GetString("AddCard_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string AddCard_ExpirationDate {
            get {
                return ResourceManager.GetString("AddCard_ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing First Name.
        /// </summary>
        public static string AddCard_FirstName {
            get {
                return ResourceManager.GetString("AddCard_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Last Name.
        /// </summary>
        public static string AddCard_LastName {
            get {
                return ResourceManager.GetString("AddCard_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string AddCard_Month {
            get {
                return ResourceManager.GetString("AddCard_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month must be between 1 and 12..
        /// </summary>
        public static string AddCard_MonthFormat {
            get {
                return ResourceManager.GetString("AddCard_MonthFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code/CCV.
        /// </summary>
        public static string AddCard_SecurityCode {
            get {
                return ResourceManager.GetString("AddCard_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string AddCard_State {
            get {
                return ResourceManager.GetString("AddCard_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string AddCard_Year {
            get {
                return ResourceManager.GetString("AddCard_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year must be full year, for example 2012..
        /// </summary>
        public static string AddCard_YearFormat {
            get {
                return ResourceManager.GetString("AddCard_YearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string AddCard_Zip {
            get {
                return ResourceManager.GetString("AddCard_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Device.
        /// </summary>
        public static string List_FromDevice {
            get {
                return ResourceManager.GetString("List_FromDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string List_Quantity {
            get {
                return ResourceManager.GetString("List_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The From device and To device must be different..
        /// </summary>
        public static string List_SameDeviceError {
            get {
                return ResourceManager.GetString("List_SameDeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Device.
        /// </summary>
        public static string List_ToDevice {
            get {
                return ResourceManager.GetString("List_ToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Notes.
        /// </summary>
        public static string PurchaseNotes {
            get {
                return ResourceManager.GetString("PurchaseNotes", resourceCulture);
            }
        }
    }
}
