//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPICCentralDL.Customization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentralDL.Customization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string MessageType_Attention {
            get {
                return ResourceManager.GetString("MessageType_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string MessageType_Information {
            get {
                return ResourceManager.GetString("MessageType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string MessageType_Marketing {
            get {
                return ResourceManager.GetString("MessageType_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string MessageType_Sale {
            get {
                return ResourceManager.GetString("MessageType_Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User.
        /// </summary>
        public static string OrganizationType_EndUser {
            get {
                return ResourceManager.GetString("OrganizationType_EndUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string OrganizationType_Host {
            get {
                return ResourceManager.GetString("OrganizationType_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearView Scan.
        /// </summary>
        public static string ScanType_ClearViewScan {
            get {
                return ResourceManager.GetString("ScanType_ClearViewScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearView Scan.
        /// </summary>
        public static string TreatmentType_ClearViewScan {
            get {
                return ResourceManager.GetString("TreatmentType_ClearViewScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string TreatmentType_FollowUp {
            get {
                return ResourceManager.GetString("TreatmentType_FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string TreatmentType_Unknown {
            get {
                return ResourceManager.GetString("TreatmentType_Unknown", resourceCulture);
            }
        }
    }
}
