//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Shared.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error has occured..
        /// </summary>
        public static string Error_DatabaseUnknown {
            get {
                return ResourceManager.GetString("Error_DatabaseUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entry must be a valid e-mail address..
        /// </summary>
        public static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {2} characters long..
        /// </summary>
        public static string Error_Length {
            get {
                return ResourceManager.GetString("Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} characters long and contain a lowercase letter, an uppercase letter, a number and a symbol..
        /// </summary>
        public static string Error_PasswordRegex {
            get {
                return ResourceManager.GetString("Error_PasswordRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Error_Required {
            get {
                return ResourceManager.GetString("Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string Error_Unspecified {
            get {
                return ResourceManager.GetString("Error_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card not found..
        /// </summary>
        public static string NotFound_CreditCard {
            get {
                return ResourceManager.GetString("NotFound_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found..
        /// </summary>
        public static string NotFound_Device {
            get {
                return ResourceManager.GetString("NotFound_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception not found..
        /// </summary>
        public static string NotFound_Exception {
            get {
                return ResourceManager.GetString("NotFound_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found..
        /// </summary>
        public static string NotFound_Image {
            get {
                return ResourceManager.GetString("NotFound_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found..
        /// </summary>
        public static string NotFound_Location {
            get {
                return ResourceManager.GetString("NotFound_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not found..
        /// </summary>
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization not found..
        /// </summary>
        public static string NotFound_Organization {
            get {
                return ResourceManager.GetString("NotFound_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient not found..
        /// </summary>
        public static string NotFound_Patient {
            get {
                return ResourceManager.GetString("NotFound_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment not found..
        /// </summary>
        public static string NotFound_Treatment {
            get {
                return ResourceManager.GetString("NotFound_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account not found..
        /// </summary>
        public static string NotFound_User {
            get {
                return ResourceManager.GetString("NotFound_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only submit every {0} seconds..
        /// </summary>
        public static string RateLimit {
            get {
                return ResourceManager.GetString("RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this credit card..
        /// </summary>
        public static string Unauthorized_CreditCard {
            get {
                return ResourceManager.GetString("Unauthorized_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this device..
        /// </summary>
        public static string Unauthorized_Device {
            get {
                return ResourceManager.GetString("Unauthorized_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this location..
        /// </summary>
        public static string Unauthorized_Location {
            get {
                return ResourceManager.GetString("Unauthorized_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this organization..
        /// </summary>
        public static string Unauthorized_Organization {
            get {
                return ResourceManager.GetString("Unauthorized_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to add this organization..
        /// </summary>
        public static string Unauthorized_OrganizationAdd {
            get {
                return ResourceManager.GetString("Unauthorized_OrganizationAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this organization..
        /// </summary>
        public static string Unauthorized_OrganizationEdit {
            get {
                return ResourceManager.GetString("Unauthorized_OrganizationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a Host organization is not allowed..
        /// </summary>
        public static string Unauthorized_OrganizationHost {
            get {
                return ResourceManager.GetString("Unauthorized_OrganizationHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this patient..
        /// </summary>
        public static string Unauthorized_Patient {
            get {
                return ResourceManager.GetString("Unauthorized_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this treatment..
        /// </summary>
        public static string Unauthorized_Treatment {
            get {
                return ResourceManager.GetString("Unauthorized_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this user account..
        /// </summary>
        public static string Unauthorized_User {
            get {
                return ResourceManager.GetString("Unauthorized_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit this user account..
        /// </summary>
        public static string Unauthorized_UserEdit {
            get {
                return ResourceManager.GetString("Unauthorized_UserEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied {0}/{1}.
        /// </summary>
        public static string UnauthorizedActionController {
            get {
                return ResourceManager.GetString("UnauthorizedActionController", resourceCulture);
            }
        }
    }
}
