//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Controllers.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central: Password Reset.
        /// </summary>
        public static string Email_SubjectPasswordReset {
            get {
                return ResourceManager.GetString("Email_SubjectPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central: New User Registration.
        /// </summary>
        public static string Email_SubjectUserRegistration {
            get {
                return ResourceManager.GetString("Email_SubjectUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string Error_AuthProvider {
            get {
                return ResourceManager.GetString("Error_AuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string Error_ChangePassword {
            get {
                return ResourceManager.GetString("Error_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset failed! Contact your system administrator..
        /// </summary>
        public static string Error_PasswordResetFailed {
            get {
                return ResourceManager.GetString("Error_PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string Error_UserCreateUnknown {
            get {
                return ResourceManager.GetString("Error_UserCreateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reset your account. The reset email has been resent..
        /// </summary>
        public static string Invalid_AccountAlreadyReset {
            get {
                return ResourceManager.GetString("Invalid_AccountAlreadyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has been locked. Please contact your system administrator..
        /// </summary>
        public static string Invalid_AccountLocked {
            get {
                return ResourceManager.GetString("Invalid_AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is new and you have not completed registration..
        /// </summary>
        public static string Invalid_AccountRegistrationIncomplete {
            get {
                return ResourceManager.GetString("Invalid_AccountRegistrationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been reset. Use the link in the email you received to complete the reset process..
        /// </summary>
        public static string Invalid_AccountReset {
            get {
                return ResourceManager.GetString("Invalid_AccountReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reset your accounts. The reset email has been resent..
        /// </summary>
        public static string Invalid_AccountsAlreadyReset {
            get {
                return ResourceManager.GetString("Invalid_AccountsAlreadyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts are new and you have not completed registration..
        /// </summary>
        public static string Invalid_AccountsRegistrationIncomplete {
            get {
                return ResourceManager.GetString("Invalid_AccountsRegistrationIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string Invalid_DuplicateUsername {
            get {
                return ResourceManager.GetString("Invalid_DuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string Invalid_EmailBad {
            get {
                return ResourceManager.GetString("Invalid_EmailBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address does not match any account..
        /// </summary>
        public static string Invalid_EmailNotMatched {
            get {
                return ResourceManager.GetString("Invalid_EmailNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address is required to reset your account..
        /// </summary>
        public static string Invalid_EmailNotSpecified {
            get {
                return ResourceManager.GetString("Invalid_EmailNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address and user name do not match those for any account..
        /// </summary>
        public static string Invalid_EmailUsernameMismatch {
            get {
                return ResourceManager.GetString("Invalid_EmailUsernameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is no longer active..
        /// </summary>
        public static string Invalid_InactiveAccount {
            get {
                return ResourceManager.GetString("Invalid_InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user registration has not been completed. Please complete your registration to log in..
        /// </summary>
        public static string Invalid_IncompleteRegistration {
            get {
                return ResourceManager.GetString("Invalid_IncompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string Invalid_PasswordBad {
            get {
                return ResourceManager.GetString("Invalid_PasswordBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a new password..
        /// </summary>
        public static string Invalid_PasswordNotSpecified {
            get {
                return ResourceManager.GetString("Invalid_PasswordNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registration PIN entered is invalid..
        /// </summary>
        public static string Invalid_RegistrationPIN {
            get {
                return ResourceManager.GetString("Invalid_RegistrationPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role specified is not valid..
        /// </summary>
        public static string Invalid_RoleSpecified {
            get {
                return ResourceManager.GetString("Invalid_RoleSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string Invalid_UsernameBad {
            get {
                return ResourceManager.GetString("Invalid_UsernameBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string Invalid_UsernamePassword {
            get {
                return ResourceManager.GetString("Invalid_UsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no pending registration..
        /// </summary>
        public static string NotFound_PendingRegistration {
            get {
                return ResourceManager.GetString("NotFound_PendingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least.
        /// </summary>
        public static string PasswordStrength_AtLeast {
            get {
                return ResourceManager.GetString("PasswordStrength_AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string PasswordStrength_Invalid {
            get {
                return ResourceManager.GetString("PasswordStrength_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character: {0}.
        /// </summary>
        public static string PasswordStrength_InvalidCharacter {
            get {
                return ResourceManager.GetString("PasswordStrength_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make stronger:.
        /// </summary>
        public static string PasswordStrength_MakeStronger {
            get {
                return ResourceManager.GetString("PasswordStrength_MakeStronger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more characters.
        /// </summary>
        public static string PasswordStrength_MoreCharsPlural {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreCharsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more character.
        /// </summary>
        public static string PasswordStrength_MoreCharsSingular {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreCharsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more numbers.
        /// </summary>
        public static string PasswordStrength_MoreDigitsPlural {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreDigitsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more number.
        /// </summary>
        public static string PasswordStrength_MoreDigitsSingular {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreDigitsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more lowercase letters.
        /// </summary>
        public static string PasswordStrength_MoreLowersPlural {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreLowersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more lowercase letter.
        /// </summary>
        public static string PasswordStrength_MoreLowersSingular {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreLowersSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more symbols.
        /// </summary>
        public static string PasswordStrength_MoreSpecialsPlural {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreSpecialsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more symbol.
        /// </summary>
        public static string PasswordStrength_MoreSpecialsSingular {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreSpecialsSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more uppercase letters.
        /// </summary>
        public static string PasswordStrength_MoreUppersPlural {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreUppersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} more uppercase letter.
        /// </summary>
        public static string PasswordStrength_MoreUppersSingular {
            get {
                return ResourceManager.GetString("PasswordStrength_MoreUppersSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spaces!.
        /// </summary>
        public static string PasswordStrength_NoSpace {
            get {
                return ResourceManager.GetString("PasswordStrength_NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong password!.
        /// </summary>
        public static string PasswordStrength_StrongPassword {
            get {
                return ResourceManager.GetString("PasswordStrength_StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too long!.
        /// </summary>
        public static string PasswordStrength_TooLong {
            get {
                return ResourceManager.GetString("PasswordStrength_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string PasswordStrength_Valid {
            get {
                return ResourceManager.GetString("PasswordStrength_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} more characters..
        /// </summary>
        public static string Username_HelpPlural {
            get {
                return ResourceManager.GetString("Username_HelpPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} more character..
        /// </summary>
        public static string Username_HelpSingular {
            get {
                return ResourceManager.GetString("Username_HelpSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already in use..
        /// </summary>
        public static string Username_InUse {
            get {
                return ResourceManager.GetString("Username_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spaces!.
        /// </summary>
        public static string Username_NoSpace {
            get {
                return ResourceManager.GetString("Username_NoSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid user name..
        /// </summary>
        public static string Username_Valid {
            get {
                return ResourceManager.GetString("Username_Valid", resourceCulture);
            }
        }
    }
}
