//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Controllers.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string AccountLogOff_LogOff {
            get {
                return ResourceManager.GetString("AccountLogOff_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string AccountLogOn_LogOn {
            get {
                return ResourceManager.GetString("AccountLogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationIndex_Configuration {
            get {
                return ResourceManager.GetString("ConfigurationIndex_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Website.
        /// </summary>
        public static string CorporateWebsite {
            get {
                return ResourceManager.GetString("CorporateWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DeviceList_Devices {
            get {
                return ResourceManager.GetString("DeviceList_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string ExceptionList_Exceptions {
            get {
                return ResourceManager.GetString("ExceptionList_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeIndex_Home {
            get {
                return ResourceManager.GetString("HomeIndex_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LocationEdit_Edit {
            get {
                return ResourceManager.GetString("LocationEdit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationList_Locations {
            get {
                return ResourceManager.GetString("LocationList_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessageList_Messages {
            get {
                return ResourceManager.GetString("MessageList_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organization.
        /// </summary>
        public static string MyOrganization {
            get {
                return ResourceManager.GetString("MyOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string OperationsIndex_Operations {
            get {
                return ResourceManager.GetString("OperationsIndex_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Organization.
        /// </summary>
        public static string OrganizationEdit_OrganizationInformation {
            get {
                return ResourceManager.GetString("OrganizationEdit_OrganizationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string OrganizationList_Organizations {
            get {
                return ResourceManager.GetString("OrganizationList_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string OrganizationSummary_Summary {
            get {
                return ResourceManager.GetString("OrganizationSummary_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string PatientSearch_Patients {
            get {
                return ResourceManager.GetString("PatientSearch_Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Search.
        /// </summary>
        public static string PatientSearch_PatientSearch {
            get {
                return ResourceManager.GetString("PatientSearch_PatientSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        public static string PatientTreatment_Definitions {
            get {
                return ResourceManager.GetString("PatientTreatment_Definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string PatientTreatment_Images {
            get {
                return ResourceManager.GetString("PatientTreatment_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string PatientTreatment_Overview {
            get {
                return ResourceManager.GetString("PatientTreatment_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Data.
        /// </summary>
        public static string PatientTreatment_RawData {
            get {
                return ResourceManager.GetString("PatientTreatment_RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Report.
        /// </summary>
        public static string PatientTreatment_RawReport {
            get {
                return ResourceManager.GetString("PatientTreatment_RawReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Comparison.
        /// </summary>
        public static string PatientTreatment_SystemComparison {
            get {
                return ResourceManager.GetString("PatientTreatment_SystemComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments.
        /// </summary>
        public static string PatientTreatments_Treatments {
            get {
                return ResourceManager.GetString("PatientTreatments_Treatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Search.
        /// </summary>
        public static string PatientTreatments_TreatmentSearch {
            get {
                return ResourceManager.GetString("PatientTreatments_TreatmentSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string PurchasesList_Purchases {
            get {
                return ResourceManager.GetString("PurchasesList_Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Center.
        /// </summary>
        public static string SupportIndex_SupportCenter {
            get {
                return ResourceManager.GetString("SupportIndex_SupportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Center ({0}).
        /// </summary>
        public static string SupportIndex_SupportCenterMessages {
            get {
                return ResourceManager.GetString("SupportIndex_SupportCenterMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string UserEdit_Edit {
            get {
                return ResourceManager.GetString("UserEdit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My Account.
        /// </summary>
        public static string UserEditMe {
            get {
                return ResourceManager.GetString("UserEditMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UserList_Users {
            get {
                return ResourceManager.GetString("UserList_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string UserView {
            get {
                return ResourceManager.GetString("UserView", resourceCulture);
            }
        }
    }
}
