//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Operation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Operation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Controllers.Operation", typeof(Operation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Active.
        /// </summary>
        public static string DevicesActive {
            get {
                return ResourceManager.GetString("DevicesActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions Received.
        /// </summary>
        public static string ExceptionsReceived {
            get {
                return ResourceManager.GetString("ExceptionsReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization: {0}.
        /// </summary>
        public static string OrganizationLabel {
            get {
                return ResourceManager.GetString("OrganizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases Made.
        /// </summary>
        public static string PurchasesMade {
            get {
                return ResourceManager.GetString("PurchasesMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Performed.
        /// </summary>
        public static string ScansPerformed {
            get {
                return ResourceManager.GetString("ScansPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Requests.
        /// </summary>
        public static string SupportRequests {
            get {
                return ResourceManager.GetString("SupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Devices.
        /// </summary>
        public static string TotalDevices {
            get {
                return ResourceManager.GetString("TotalDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Exceptions.
        /// </summary>
        public static string TotalExceptions {
            get {
                return ResourceManager.GetString("TotalExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Organizations.
        /// </summary>
        public static string TotalOrganizations {
            get {
                return ResourceManager.GetString("TotalOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchases.
        /// </summary>
        public static string TotalPurchases {
            get {
                return ResourceManager.GetString("TotalPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Scans.
        /// </summary>
        public static string TotalScans {
            get {
                return ResourceManager.GetString("TotalScans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TotalUsers {
            get {
                return ResourceManager.GetString("TotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Online.
        /// </summary>
        public static string UsersOnline {
            get {
                return ResourceManager.GetString("UsersOnline", resourceCulture);
            }
        }
    }
}
