//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Widgets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Widgets() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Controllers.Widgets", typeof(Widgets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location {0} has at least one device with less than {1} scans remaining..
        /// </summary>
        public static string Alert_ScansRemaining {
            get {
                return ResourceManager.GetString("Alert_ScansRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alert_Title {
            get {
                return ResourceManager.GetString("Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location {0} has at least one device with zero scans remaining..
        /// </summary>
        public static string Alert_ZeroScansRemaining {
            get {
                return ResourceManager.GetString("Alert_ZeroScansRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DeviceState_Devices {
            get {
                return ResourceManager.GetString("DeviceState_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device State.
        /// </summary>
        public static string DeviceState_DeviceState {
            get {
                return ResourceManager.GetString("DeviceState_DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string DeviceState_LocationName {
            get {
                return ResourceManager.GetString("DeviceState_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string DeviceState_SerialNumber {
            get {
                return ResourceManager.GetString("DeviceState_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string DeviceState_Title {
            get {
                return ResourceManager.GetString("DeviceState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RecentActivity_Description {
            get {
                return ResourceManager.GetString("RecentActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Time.
        /// </summary>
        public static string RecentActivity_EventTime {
            get {
                return ResourceManager.GetString("RecentActivity_EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string RecentActivity_Exception {
            get {
                return ResourceManager.GetString("RecentActivity_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Created.
        /// </summary>
        public static string RecentActivity_PatientCreated {
            get {
                return ResourceManager.GetString("RecentActivity_PatientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity_Title {
            get {
                return ResourceManager.GetString("RecentActivity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string RecentActivity_Treatment {
            get {
                return ResourceManager.GetString("RecentActivity_Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string RecentActivity_Type {
            get {
                return ResourceManager.GetString("RecentActivity_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created.
        /// </summary>
        public static string RecentActivity_UserCreated {
            get {
                return ResourceManager.GetString("RecentActivity_UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string RecentActivity_ViewException {
            get {
                return ResourceManager.GetString("RecentActivity_ViewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string RecentActivity_ViewTreatment {
            get {
                return ResourceManager.GetString("RecentActivity_ViewTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments ({0}).
        /// </summary>
        public static string RecentActivity_ViewTreatments {
            get {
                return ResourceManager.GetString("RecentActivity_ViewTreatments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string RecentActivity_ViewUser {
            get {
                return ResourceManager.GetString("RecentActivity_ViewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string RecentActivityController_ViewPatient {
            get {
                return ResourceManager.GetString("RecentActivityController_ViewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments.
        /// </summary>
        public static string Treatments_Title {
            get {
                return ResourceManager.GetString("Treatments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments in {0}.
        /// </summary>
        public static string Treatments_TreatmentsInYear {
            get {
                return ResourceManager.GetString("Treatments_TreatmentsInYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments Last Year.
        /// </summary>
        public static string Treatments_TreatmentsLastYear {
            get {
                return ResourceManager.GetString("Treatments_TreatmentsLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatments This Year.
        /// </summary>
        public static string Treatments_TreatmentsThisYear {
            get {
                return ResourceManager.GetString("Treatments_TreatmentsThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find location..
        /// </summary>
        public static string Weather_LocationError {
            get {
                return ResourceManager.GetString("Weather_LocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather_Title {
            get {
                return ResourceManager.GetString("Weather_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put content here..
        /// </summary>
        public static string Widget_Content {
            get {
                return ResourceManager.GetString("Widget_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while rendering widget of type: {0}.
        /// </summary>
        public static string Widget_RenderError {
            get {
                return ResourceManager.GetString("Widget_RenderError", resourceCulture);
            }
        }
    }
}
