//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ChangePassword_Cancel {
            get {
                return ResourceManager.GetString("ChangePassword_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password for {0}.
        /// </summary>
        public static string ChangePassword_ChangePasswordFor {
            get {
                return ResourceManager.GetString("ChangePassword_ChangePasswordFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current/New Password.
        /// </summary>
        public static string ChangePassword_CurrentPassword {
            get {
                return ResourceManager.GetString("ChangePassword_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string ChangePassword_Errors {
            get {
                return ResourceManager.GetString("ChangePassword_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string ChangePassword_MinimumLength {
            get {
                return ResourceManager.GetString("ChangePassword_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ChangePassword_Save {
            get {
                return ResourceManager.GetString("ChangePassword_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ChangePasswordSuccess_Continue {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ChangePasswordSuccess_Message {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordSuccess_Title {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LogOn_Errors {
            get {
                return ResourceManager.GetString("LogOn_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot!.
        /// </summary>
        public static string LogOn_IForgot {
            get {
                return ResourceManager.GetString("LogOn_IForgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and password to log in..
        /// </summary>
        public static string LogOn_Message {
            get {
                return ResourceManager.GetString("LogOn_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset ....
        /// </summary>
        public static string LogOn_Reset {
            get {
                return ResourceManager.GetString("LogOn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn_Submit {
            get {
                return ResourceManager.GetString("LogOn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOn_Title {
            get {
                return ResourceManager.GetString("LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string Register_AccountInformation {
            get {
                return ResourceManager.GetString("Register_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Register_Errors {
            get {
                return ResourceManager.GetString("Register_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete New Account Registration.
        /// </summary>
        public static string Register_Heading {
            get {
                return ResourceManager.GetString("Register_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the form below to complete your account registration..
        /// </summary>
        public static string Register_Message {
            get {
                return ResourceManager.GetString("Register_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are required to be a minimum of {0} characters in length..
        /// </summary>
        public static string Register_MinimumLength {
            get {
                return ResourceManager.GetString("Register_MinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Submit {
            get {
                return ResourceManager.GetString("Register_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Reset_Errors {
            get {
                return ResourceManager.GetString("Reset_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on ....
        /// </summary>
        public static string Reset_LogOn {
            get {
                return ResourceManager.GetString("Reset_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and email address to reset your account..
        /// </summary>
        public static string Reset_Message {
            get {
                return ResourceManager.GetString("Reset_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I remembered!.
        /// </summary>
        public static string Reset_Remembered {
            get {
                return ResourceManager.GetString("Reset_Remembered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Account.
        /// </summary>
        public static string Reset_Title {
            get {
                return ResourceManager.GetString("Reset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        public static string ResetCompletion_CreateNew {
            get {
                return ResourceManager.GetString("ResetCompletion_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string ResetCompletion_Errors {
            get {
                return ResourceManager.GetString("ResetCompletion_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset the password on your account..
        /// </summary>
        public static string ResetCompletion_Message {
            get {
                return ResourceManager.GetString("ResetCompletion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have multiple accounts with the same email address.  Please select the one to reset..
        /// </summary>
        public static string ResetCompletion_MultipleAccounts {
            get {
                return ResourceManager.GetString("ResetCompletion_MultipleAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ResetCompletion_Next {
            get {
                return ResourceManager.GetString("ResetCompletion_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetCompletion_Reset {
            get {
                return ResourceManager.GetString("ResetCompletion_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Account.
        /// </summary>
        public static string ResetCompletion_SelectAccount {
            get {
                return ResourceManager.GetString("ResetCompletion_SelectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset Completion.
        /// </summary>
        public static string ResetCompletion_Title {
            get {
                return ResourceManager.GetString("ResetCompletion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully.  You may now {0} using your new password..
        /// </summary>
        public static string ResetCompletionSuccess_Message {
            get {
                return ResourceManager.GetString("ResetCompletionSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Account Reset.
        /// </summary>
        public static string ResetCompletionSuccess_Title {
            get {
                return ResourceManager.GetString("ResetCompletionSuccess_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Password Reset.
        /// </summary>
        public static string ResetEmailPartial_CompleteLink {
            get {
                return ResourceManager.GetString("ResetEmailPartial_CompleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},.
        /// </summary>
        public static string ResetEmailPartial_Greeting {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello EPIC Central User,.
        /// </summary>
        public static string ResetEmailPartial_GreetingGeneric {
            get {
                return ResourceManager.GetString("ResetEmailPartial_GreetingGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not reset your password on the EPIC Central site, please
        ///    contact EPIC Central support immediately..
        /// </summary>
        public static string ResetEmailPartial_Instruction2 {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Instruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to set a new password before you can log in.
        ///	If you have more that one account with this e-mail address, you will
        ///	be able to choose the account on which to set a new password.
        ///	Until you complete the reset process, you will not be able to log in
        ///	to any account..
        /// </summary>
        public static string ResetEmailPartial_Instructions {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        ///Please click the link below to complete the password reset process:.
        /// </summary>
        public static string ResetEmailPartial_Message {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string ResetEmailPartial_Salutation {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EPIC Central Team.
        /// </summary>
        public static string ResetEmailPartial_SalutationName {
            get {
                return ResourceManager.GetString("ResetEmailPartial_SalutationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central: Password Reset Email.
        /// </summary>
        public static string ResetEmailPartial_Title {
            get {
                return ResourceManager.GetString("ResetEmailPartial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been reset.
        ///An email has been sent to your email address.
        ///When you recieve the email, click the link provided to complete the reset process.
        ///Your account is current restricted and you cannot log in until you complete the process..
        /// </summary>
        public static string ResetSuccess_Message {
            get {
                return ResourceManager.GetString("ResetSuccess_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Reset.
        /// </summary>
        public static string ResetSuccess_Title {
            get {
                return ResourceManager.GetString("ResetSuccess_Title", resourceCulture);
            }
        }
    }
}
