//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string Configuration_Active {
            get {
                return ResourceManager.GetString("Configuration_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Configuration_EditSetting {
            get {
                return ResourceManager.GetString("Configuration_EditSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit System Setting.
        /// </summary>
        public static string Configuration_EditSettingTitle {
            get {
                return ResourceManager.GetString("Configuration_EditSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string Configuration_Effective {
            get {
                return ResourceManager.GetString("Configuration_Effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Maximum.
        /// </summary>
        public static string Configuration_Max {
            get {
                return ResourceManager.GetString("Configuration_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Minimum.
        /// </summary>
        public static string Configuration_Min {
            get {
                return ResourceManager.GetString("Configuration_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Configuration_RateEdit {
            get {
                return ResourceManager.GetString("Configuration_RateEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Scan Rate.
        /// </summary>
        public static string Configuration_RateEditTitle {
            get {
                return ResourceManager.GetString("Configuration_RateEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Per Scan.
        /// </summary>
        public static string Configuration_RatePerScan {
            get {
                return ResourceManager.GetString("Configuration_RatePerScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Rates.
        /// </summary>
        public static string Configuration_Rates {
            get {
                return ResourceManager.GetString("Configuration_Rates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Rate ID.
        /// </summary>
        public static string Configuration_ScanRateId {
            get {
                return ResourceManager.GetString("Configuration_ScanRateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Type.
        /// </summary>
        public static string Configuration_ScanType {
            get {
                return ResourceManager.GetString("Configuration_ScanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Name.
        /// </summary>
        public static string Configuration_SettingName {
            get {
                return ResourceManager.GetString("Configuration_SettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string Configuration_Settings {
            get {
                return ResourceManager.GetString("Configuration_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Value.
        /// </summary>
        public static string Configuration_SettingValue {
            get {
                return ResourceManager.GetString("Configuration_SettingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string EditRate_Administration {
            get {
                return ResourceManager.GetString("EditRate_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors proccessing the request:.
        /// </summary>
        public static string EditRate_Errors {
            get {
                return ResourceManager.GetString("EditRate_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Scan Rate.
        /// </summary>
        public static string EditRate_Title {
            get {
                return ResourceManager.GetString("EditRate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string EditSetting_Administration {
            get {
                return ResourceManager.GetString("EditSetting_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors processing the request:.
        /// </summary>
        public static string EditSetting_Errors {
            get {
                return ResourceManager.GetString("EditSetting_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit System Settings.
        /// </summary>
        public static string EditSetting_Title {
            get {
                return ResourceManager.GetString("EditSetting_Title", resourceCulture);
            }
        }
    }
}
