//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Device {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Device() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Device", typeof(Device).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Edit_Administration {
            get {
                return ResourceManager.GetString("Edit_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred while editing the device:.
        /// </summary>
        public static string Edit_Errors {
            get {
                return ResourceManager.GetString("Edit_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retiring a device takes it &lt;b&gt;permanently&lt;/b&gt; out of service.
        ///	It cannot be reinitialized or made active again.
        ///	Are you sure you want to retire this device?
        ///    Please confirm..
        /// </summary>
        public static string Edit_Retiring {
            get {
                return ResourceManager.GetString("Edit_Retiring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Device Retirement.
        /// </summary>
        public static string Edit_RetiringTitle {
            get {
                return ResourceManager.GetString("Edit_RetiringTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearView Device.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearView Devices.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        public static string ListFull_AddDevice {
            get {
                return ResourceManager.GetString("ListFull_AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ListFull_Edit {
            get {
                return ResourceManager.GetString("ListFull_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device.
        /// </summary>
        public static string ListFull_EditDevice {
            get {
                return ResourceManager.GetString("ListFull_EditDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Report.
        /// </summary>
        public static string ListFull_LastReport {
            get {
                return ResourceManager.GetString("ListFull_LastReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ListFull_Location {
            get {
                return ResourceManager.GetString("ListFull_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string ListFull_Organization {
            get {
                return ResourceManager.GetString("ListFull_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string ListFull_Revision {
            get {
                return ResourceManager.GetString("ListFull_Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Left.
        /// </summary>
        public static string ListFull_ScansLeft {
            get {
                return ResourceManager.GetString("ListFull_ScansLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial #.
        /// </summary>
        public static string ListFull_Serial {
            get {
                return ResourceManager.GetString("ListFull_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ListFull_State {
            get {
                return ResourceManager.GetString("ListFull_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ListFull_View {
            get {
                return ResourceManager.GetString("ListFull_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Details.
        /// </summary>
        public static string ListFullControl_DeviceDetails {
            get {
                return ResourceManager.GetString("ListFullControl_DeviceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Done.
        /// </summary>
        public static string ListFullControl_ScansDone {
            get {
                return ResourceManager.GetString("ListFullControl_ScansDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string ListLimitedControl_Issued {
            get {
                return ResourceManager.GetString("ListLimitedControl_Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Report.
        /// </summary>
        public static string ListLimitedControl_LastReport {
            get {
                return ResourceManager.GetString("ListLimitedControl_LastReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ListLimitedControl_Location {
            get {
                return ResourceManager.GetString("ListLimitedControl_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Level.
        /// </summary>
        public static string ListLimitedControl_RevisionLevel {
            get {
                return ResourceManager.GetString("ListLimitedControl_RevisionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Done.
        /// </summary>
        public static string ListLimitedControl_ScansDone {
            get {
                return ResourceManager.GetString("ListLimitedControl_ScansDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Left.
        /// </summary>
        public static string ListLimitedControl_ScansLeft {
            get {
                return ResourceManager.GetString("ListLimitedControl_ScansLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string ListLimitedControl_SerialNumber {
            get {
                return ResourceManager.GetString("ListLimitedControl_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string ListLimitedControl_State {
            get {
                return ResourceManager.GetString("ListLimitedControl_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device State.
        /// </summary>
        public static string View_DeviceState {
            get {
                return ResourceManager.GetString("View_DeviceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued Time.
        /// </summary>
        public static string View_IssuedTime {
            get {
                return ResourceManager.GetString("View_IssuedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Report Time.
        /// </summary>
        public static string View_LastReport {
            get {
                return ResourceManager.GetString("View_LastReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string View_LocationName {
            get {
                return ResourceManager.GetString("View_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string View_OrganizationName {
            get {
                return ResourceManager.GetString("View_OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Level.
        /// </summary>
        public static string View_RevisionLevel {
            get {
                return ResourceManager.GetString("View_RevisionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Available.
        /// </summary>
        public static string View_ScansAvailable {
            get {
                return ResourceManager.GetString("View_ScansAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Completed.
        /// </summary>
        public static string View_ScansCompleted {
            get {
                return ResourceManager.GetString("View_ScansCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string View_SerialNumber {
            get {
                return ResourceManager.GetString("View_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearView Device.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID Qualifier.
        /// </summary>
        public static string View_UidQualifier {
            get {
                return ResourceManager.GetString("View_UidQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Identifier.
        /// </summary>
        public static string View_UniqueIdentifier {
            get {
                return ResourceManager.GetString("View_UniqueIdentifier", resourceCulture);
            }
        }
    }
}
