//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Exception {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exception() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Exception", typeof(Exception).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string List_Device {
            get {
                return ResourceManager.GetString("List_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception ID.
        /// </summary>
        public static string List_ExceptionId {
            get {
                return ResourceManager.GetString("List_ExceptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string List_ExceptionTitle {
            get {
                return ResourceManager.GetString("List_ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string List_LocationName {
            get {
                return ResourceManager.GetString("List_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string List_LogTime {
            get {
                return ResourceManager.GetString("List_LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string List_MachineName {
            get {
                return ResourceManager.GetString("List_MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Time.
        /// </summary>
        public static string List_ReceivedTime {
            get {
                return ResourceManager.GetString("List_ReceivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string List_View {
            get {
                return ResourceManager.GetString("List_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Exception.
        /// </summary>
        public static string List_ViewException {
            get {
                return ResourceManager.GetString("List_ViewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Version.
        /// </summary>
        public static string View_CLRVersion {
            get {
                return ResourceManager.GetString("View_CLRVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        public static string View_DeviceId {
            get {
                return ResourceManager.GetString("View_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string View_ExceptionTitle {
            get {
                return ResourceManager.GetString("View_ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string View_LocationName {
            get {
                return ResourceManager.GetString("View_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string View_LogTime {
            get {
                return ResourceManager.GetString("View_LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine OS.
        /// </summary>
        public static string View_MachineOS {
            get {
                return ResourceManager.GetString("View_MachineOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maching Name.
        /// </summary>
        public static string View_MachingName {
            get {
                return ResourceManager.GetString("View_MachingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        public static string View_MemoryUsage {
            get {
                return ResourceManager.GetString("View_MemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string View_Message {
            get {
                return ResourceManager.GetString("View_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Time.
        /// </summary>
        public static string View_ReceivedTime {
            get {
                return ResourceManager.GetString("View_ReceivedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Exception ID.
        /// </summary>
        public static string View_RemoteId {
            get {
                return ResourceManager.GetString("View_RemoteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial #.
        /// </summary>
        public static string View_Serial {
            get {
                return ResourceManager.GetString("View_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string View_StackTrace {
            get {
                return ResourceManager.GetString("View_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Details.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string View_User {
            get {
                return ResourceManager.GetString("View_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string View_Version {
            get {
                return ResourceManager.GetString("View_Version", resourceCulture);
            }
        }
    }
}
