//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Organization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Organization", typeof(Organization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string Edit_Active {
            get {
                return ResourceManager.GetString("Edit_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Edit_Cancel {
            get {
                return ResourceManager.GetString("Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the organization information, pleast correct the errors below..
        /// </summary>
        public static string Edit_Error {
            get {
                return ResourceManager.GetString("Edit_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Edit_Name {
            get {
                return ResourceManager.GetString("Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Information.
        /// </summary>
        public static string Edit_OrganizationInformation {
            get {
                return ResourceManager.GetString("Edit_OrganizationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Edit_Save {
            get {
                return ResourceManager.GetString("Edit_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Edit_Type {
            get {
                return ResourceManager.GetString("Edit_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Organization.
        /// </summary>
        public static string List_AddOrganization {
            get {
                return ResourceManager.GetString("List_AddOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string List_Edit {
            get {
                return ResourceManager.GetString("List_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization.
        /// </summary>
        public static string List_EditOrganization {
            get {
                return ResourceManager.GetString("List_EditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations ({0}).
        /// </summary>
        public static string List_FormatLocations {
            get {
                return ResourceManager.GetString("List_FormatLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users ({0}).
        /// </summary>
        public static string List_FormatUsers {
            get {
                return ResourceManager.GetString("List_FormatUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string List_Name {
            get {
                return ResourceManager.GetString("List_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string List_Type {
            get {
                return ResourceManager.GetString("List_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Identifier.
        /// </summary>
        public static string List_UniqueID {
            get {
                return ResourceManager.GetString("List_UniqueID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary_Title {
            get {
                return ResourceManager.GetString("Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string View_Edit {
            get {
                return ResourceManager.GetString("View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string View_Name {
            get {
                return ResourceManager.GetString("View_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Information.
        /// </summary>
        public static string View_OrganizationInformation {
            get {
                return ResourceManager.GetString("View_OrganizationInformation", resourceCulture);
            }
        }
    }
}
