//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Purchase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Purchase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Purchase", typeof(Purchase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add purchase, please correct the errors..
        /// </summary>
        public static string Add_Error {
            get {
                return ResourceManager.GetString("Add_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the card was unsuccessful, please correct the errors below..
        /// </summary>
        public static string AddCard_Error {
            get {
                return ResourceManager.GetString("AddCard_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Card.
        /// </summary>
        public static string AddCard_Title {
            get {
                return ResourceManager.GetString("AddCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Checkout_Card {
            get {
                return ResourceManager.GetString("Checkout_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error checking out:.
        /// </summary>
        public static string Checkout_Errors {
            get {
                return ResourceManager.GetString("Checkout_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a credit card:.
        /// </summary>
        public static string Checkout_Message {
            get {
                return ResourceManager.GetString("Checkout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Checkout_Purchase {
            get {
                return ResourceManager.GetString("Checkout_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Checkout_Quantity {
            get {
                return ResourceManager.GetString("Checkout_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Checkout_Rate {
            get {
                return ResourceManager.GetString("Checkout_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Purchase.
        /// </summary>
        public static string Checkout_Title {
            get {
                return ResourceManager.GetString("Checkout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0:C}.
        /// </summary>
        public static string Checkout_Total {
            get {
                return ResourceManager.GetString("Checkout_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors while editing the card:.
        /// </summary>
        public static string EditCard_Errors {
            get {
                return ResourceManager.GetString("EditCard_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank to leave unchanged..
        /// </summary>
        public static string EditCard_LeaveBlank {
            get {
                return ResourceManager.GetString("EditCard_LeaveBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string EditCard_Title {
            get {
                return ResourceManager.GetString("EditCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string List_AmountPaid {
            get {
                return ResourceManager.GetString("List_AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string List_Device {
            get {
                return ResourceManager.GetString("List_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors occurred while processing the transaction:.
        /// </summary>
        public static string List_Errors {
            get {
                return ResourceManager.GetString("List_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string List_LocationName {
            get {
                return ResourceManager.GetString("List_LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase.
        /// </summary>
        public static string List_NewPurchase {
            get {
                return ResourceManager.GetString("List_NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Notes.
        /// </summary>
        public static string List_PurchaseNotes {
            get {
                return ResourceManager.GetString("List_PurchaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Time.
        /// </summary>
        public static string List_PurchaseTime {
            get {
                return ResourceManager.GetString("List_PurchaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scans Purchased.
        /// </summary>
        public static string List_ScansPurchased {
            get {
                return ResourceManager.GetString("List_ScansPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase History.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string List_Transfer {
            get {
                return ResourceManager.GetString("List_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Purchases.
        /// </summary>
        public static string List_TransferPurchases {
            get {
                return ResourceManager.GetString("List_TransferPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string New_AccountNumber {
            get {
                return ResourceManager.GetString("New_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Card.
        /// </summary>
        public static string New_AddCard {
            get {
                return ResourceManager.GetString("New_AddCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string New_Address {
            get {
                return ResourceManager.GetString("New_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Cart.
        /// </summary>
        public static string New_AddToCart {
            get {
                return ResourceManager.GetString("New_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Cards.
        /// </summary>
        public static string New_Cards {
            get {
                return ResourceManager.GetString("New_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string New_Cart {
            get {
                return ResourceManager.GetString("New_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string New_Checkout {
            get {
                return ResourceManager.GetString("New_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        public static string New_CreditCard {
            get {
                return ResourceManager.GetString("New_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string New_Device {
            get {
                return ResourceManager.GetString("New_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string New_Edit {
            get {
                return ResourceManager.GetString("New_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Card.
        /// </summary>
        public static string New_EditCard {
            get {
                return ResourceManager.GetString("New_EditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string New_FirstName {
            get {
                return ResourceManager.GetString("New_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string New_LastName {
            get {
                return ResourceManager.GetString("New_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string New_Location {
            get {
                return ResourceManager.GetString("New_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase.
        /// </summary>
        public static string New_NewPurchase {
            get {
                return ResourceManager.GetString("New_NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string New_Price {
            get {
                return ResourceManager.GetString("New_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string New_Quantity {
            get {
                return ResourceManager.GetString("New_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate (price per scan).
        /// </summary>
        public static string New_Rate {
            get {
                return ResourceManager.GetString("New_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string New_Remove {
            get {
                return ResourceManager.GetString("New_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next screen will allow you to confirm the purchase before the payment is authorized..
        /// </summary>
        public static string New_TheNextScreen {
            get {
                return ResourceManager.GetString("New_TheNextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase.
        /// </summary>
        public static string New_Title {
            get {
                return ResourceManager.GetString("New_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string New_Total {
            get {
                return ResourceManager.GetString("New_Total", resourceCulture);
            }
        }
    }
}
