//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data from server.
        /// </summary>
        public static string DataTables_Loading {
            get {
                return ResourceManager.GetString("DataTables_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column ascending.
        /// </summary>
        public static string DataTablesPartial_ARIAAsc {
            get {
                return ResourceManager.GetString("DataTablesPartial_ARIAAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : activate to sort column descending.
        /// </summary>
        public static string DataTablesPartial_ARIADesc {
            get {
                return ResourceManager.GetString("DataTablesPartial_ARIADesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DataTablesPartial_Cancel {
            get {
                return ResourceManager.GetString("DataTablesPartial_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string DataTablesPartial_Close {
            get {
                return ResourceManager.GetString("DataTablesPartial_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered from _MAX_ total entries).
        /// </summary>
        public static string DataTablesPartial_Filtered {
            get {
                return ResourceManager.GetString("DataTablesPartial_Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string DataTablesPartial_First {
            get {
                return ResourceManager.GetString("DataTablesPartial_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string DataTablesPartial_Last {
            get {
                return ResourceManager.GetString("DataTablesPartial_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string DataTablesPartial_Loading {
            get {
                return ResourceManager.GetString("DataTablesPartial_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DataTablesPartial_Next {
            get {
                return ResourceManager.GetString("DataTablesPartial_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available in table..
        /// </summary>
        public static string DataTablesPartial_NoData {
            get {
                return ResourceManager.GetString("DataTablesPartial_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string DataTablesPartial_NoMatching {
            get {
                return ResourceManager.GetString("DataTablesPartial_NoMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string DataTablesPartial_Previous {
            get {
                return ResourceManager.GetString("DataTablesPartial_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string DataTablesPartial_Processing {
            get {
                return ResourceManager.GetString("DataTablesPartial_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DataTablesPartial_Save {
            get {
                return ResourceManager.GetString("DataTablesPartial_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string DataTablesPartial_Search {
            get {
                return ResourceManager.GetString("DataTablesPartial_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string DataTablesPartial_ShowEntries {
            get {
                return ResourceManager.GetString("DataTablesPartial_ShowEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string DataTablesPartial_Showing {
            get {
                return ResourceManager.GetString("DataTablesPartial_Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing 0 to 0 of 0 entries.
        /// </summary>
        public static string DataTablesPartial_ShowingEmpty {
            get {
                return ResourceManager.GetString("DataTablesPartial_ShowingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8501 East Princess Drive, Suite 100.
        /// </summary>
        public static string EmailLayout_Address {
            get {
                return ResourceManager.GetString("EmailLayout_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scottsdale, Arizona 85255.
        /// </summary>
        public static string EmailLayout_CityStateZip {
            get {
                return ResourceManager.GetString("EmailLayout_CityStateZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} EPIC Research &amp; Diagnostics, Inc. All Rights Reserved..
        /// </summary>
        public static string EmailLayout_Copyright {
            get {
                return ResourceManager.GetString("EmailLayout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@epicdiagnostics.com.
        /// </summary>
        public static string EmailLayout_Email {
            get {
                return ResourceManager.GetString("EmailLayout_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email : {0}.
        /// </summary>
        public static string EmailLayout_EmailLabel {
            get {
                return ResourceManager.GetString("EmailLayout_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Research &amp; Diagnostics, Inc..
        /// </summary>
        public static string EmailLayout_EPICResearch {
            get {
                return ResourceManager.GetString("EmailLayout_EPICResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel : 480.477.5242, Fax : 480.292.7933.
        /// </summary>
        public static string EmailLayout_Phone {
            get {
                return ResourceManager.GetString("EmailLayout_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central Email.
        /// </summary>
        public static string EmailLayout_Title {
            get {
                return ResourceManager.GetString("EmailLayout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8501 East Princess Drive, Suite 100.
        /// </summary>
        public static string Layout_Address {
            get {
                return ResourceManager.GetString("Layout_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scottsdale, Arizona 85255.
        /// </summary>
        public static string Layout_CityStateZip {
            get {
                return ResourceManager.GetString("Layout_CityStateZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} EPIC Research &amp; Diagnostics, Inc. All Rights Reserved..
        /// </summary>
        public static string Layout_Copyright {
            get {
                return ResourceManager.GetString("Layout_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@epicdiagnostics.com.
        /// </summary>
        public static string Layout_Email {
            get {
                return ResourceManager.GetString("Layout_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email : {0}.
        /// </summary>
        public static string Layout_EmailLabel {
            get {
                return ResourceManager.GetString("Layout_EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central.
        /// </summary>
        public static string Layout_EPICCentral {
            get {
                return ResourceManager.GetString("Layout_EPICCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Command Center.
        /// </summary>
        public static string Layout_EPICCommandCenter {
            get {
                return ResourceManager.GetString("Layout_EPICCommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Research &amp; Diagnostics, Inc..
        /// </summary>
        public static string Layout_EPICResearch {
            get {
                return ResourceManager.GetString("Layout_EPICResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel : 480.477.5242, Fax : 480.292.7933.
        /// </summary>
        public static string Layout_Phone {
            get {
                return ResourceManager.GetString("Layout_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        public static string LogOnPartial_LogOff {
            get {
                return ResourceManager.GetString("LogOnPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On.
        /// </summary>
        public static string LogOnPartial_LogOn {
            get {
                return ResourceManager.GetString("LogOnPartial_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string LogOnPartial_WelcomeLabel {
            get {
                return ResourceManager.GetString("LogOnPartial_WelcomeLabel", resourceCulture);
            }
        }
    }
}
