//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Support {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Support() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Support", typeof(Support).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the message was unsuccessful, please correct the errors below..
        /// </summary>
        public static string Compose_Error {
            get {
                return ResourceManager.GetString("Compose_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving draft....
        /// </summary>
        public static string Compose_SavingDraft {
            get {
                return ResourceManager.GetString("Compose_SavingDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose Message.
        /// </summary>
        public static string Compose_Title {
            get {
                return ResourceManager.GetString("Compose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Message_Forward {
            get {
                return ResourceManager.GetString("Message_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Message_Reply {
            get {
                return ResourceManager.GetString("Message_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply All.
        /// </summary>
        public static string Message_ReplyAll {
            get {
                return ResourceManager.GetString("Message_ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Message_Sender {
            get {
                return ResourceManager.GetString("Message_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Message_Subject {
            get {
                return ResourceManager.GetString("Message_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Message_To {
            get {
                return ResourceManager.GetString("Message_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compose a New Message.
        /// </summary>
        public static string Support_Compose {
            get {
                return ResourceManager.GetString("Support_Compose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Received.
        /// </summary>
        public static string Support_DateReceived {
            get {
                return ResourceManager.GetString("Support_DateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Support_Delete {
            get {
                return ResourceManager.GetString("Support_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        public static string Support_Empty {
            get {
                return ResourceManager.GetString("Support_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait up to 2 minutes before you can access your Support Center account..
        /// </summary>
        public static string Support_MustWait {
            get {
                return ResourceManager.GetString("Support_MustWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Support Center account has not been setup.  Please contact the system administrator..
        /// </summary>
        public static string Support_NotSetup {
            get {
                return ResourceManager.GetString("Support_NotSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Support_Send {
            get {
                return ResourceManager.GetString("Support_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Support_Sender {
            get {
                return ResourceManager.GetString("Support_Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Support_Subject {
            get {
                return ResourceManager.GetString("Support_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Center.
        /// </summary>
        public static string Support_Title {
            get {
                return ResourceManager.GetString("Support_Title", resourceCulture);
            }
        }
    }
}
