//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Treatment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Treatment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.Treatment", typeof(Treatment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Images.
        /// </summary>
        public static string Images_CalibrationImages {
            get {
                return ResourceManager.GetString("Images_CalibrationImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energized Images with Capacitive Barrier.
        /// </summary>
        public static string Images_EnergizedImagesWFilter {
            get {
                return ResourceManager.GetString("Images_EnergizedImagesWFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energized Images without Capacitive Barrier.
        /// </summary>
        public static string Images_EnergizedImagesWOFilter {
            get {
                return ResourceManager.GetString("Images_EnergizedImagesWOFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Images_Left {
            get {
                return ResourceManager.GetString("Images_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Images_Right {
            get {
                return ResourceManager.GetString("Images_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Finger Image Available.
        /// </summary>
        public static string NoImageAvailable {
            get {
                return ResourceManager.GetString("NoImageAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Group.
        /// </summary>
        public static string RawReport_AnalysisGroup {
            get {
                return ResourceManager.GetString("RawReport_AnalysisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomic Odds Ratio.
        /// </summary>
        public static string RawReport_AutonomicOddsRatio {
            get {
                return ResourceManager.GetString("RawReport_AutonomicOddsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomic Score.
        /// </summary>
        public static string RawReport_AutonomicScore {
            get {
                return ResourceManager.GetString("RawReport_AutonomicScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Base Score(L).
        /// </summary>
        public static string RawReport_EPICBaseScoreL {
            get {
                return ResourceManager.GetString("RawReport_EPICBaseScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Base Score(R).
        /// </summary>
        public static string RawReport_EPICBaseScoreR {
            get {
                return ResourceManager.GetString("RawReport_EPICBaseScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Bonus Score(L).
        /// </summary>
        public static string RawReport_EPICBonusScoreL {
            get {
                return ResourceManager.GetString("RawReport_EPICBonusScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Bonus Score(R).
        /// </summary>
        public static string RawReport_EPICBonusScoreR {
            get {
                return ResourceManager.GetString("RawReport_EPICBonusScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Rank(L).
        /// </summary>
        public static string RawReport_EPICRankL {
            get {
                return ResourceManager.GetString("RawReport_EPICRankL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Rank(R).
        /// </summary>
        public static string RawReport_EPICRankR {
            get {
                return ResourceManager.GetString("RawReport_EPICRankR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Score(L).
        /// </summary>
        public static string RawReport_EPICScoreL {
            get {
                return ResourceManager.GetString("RawReport_EPICScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Score(R).
        /// </summary>
        public static string RawReport_EPICScoreR {
            get {
                return ResourceManager.GetString("RawReport_EPICScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Total Score(L).
        /// </summary>
        public static string RawReport_EPICTotalScoreL {
            get {
                return ResourceManager.GetString("RawReport_EPICTotalScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Total Score(R).
        /// </summary>
        public static string RawReport_EPICTotalScoreR {
            get {
                return ResourceManager.GetString("RawReport_EPICTotalScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger/Sector.
        /// </summary>
        public static string RawReport_FingerSector {
            get {
                return ResourceManager.GetString("RawReport_FingerSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Rank(L).
        /// </summary>
        public static string RawReport_LRRankL {
            get {
                return ResourceManager.GetString("RawReport_LRRankL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Rank(R).
        /// </summary>
        public static string RawReport_LRRankR {
            get {
                return ResourceManager.GetString("RawReport_LRRankR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Score(L).
        /// </summary>
        public static string RawReport_LRScoreL {
            get {
                return ResourceManager.GetString("RawReport_LRScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LR Score(R).
        /// </summary>
        public static string RawReport_LRScoreR {
            get {
                return ResourceManager.GetString("RawReport_LRScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organ.
        /// </summary>
        public static string RawReport_Organ {
            get {
                return ResourceManager.GetString("RawReport_Organ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organ System.
        /// </summary>
        public static string RawReport_OrganSystem {
            get {
                return ResourceManager.GetString("RawReport_OrganSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Odds Ratio.
        /// </summary>
        public static string RawReport_PhysicalOddsRatio {
            get {
                return ResourceManager.GetString("RawReport_PhysicalOddsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Score.
        /// </summary>
        public static string RawReport_PhysicalScore {
            get {
                return ResourceManager.GetString("RawReport_PhysicalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Score(L).
        /// </summary>
        public static string RawReport_ReportScoreL {
            get {
                return ResourceManager.GetString("RawReport_ReportScoreL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Score(R).
        /// </summary>
        public static string RawReport_ReportScoreR {
            get {
                return ResourceManager.GetString("RawReport_ReportScoreR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomic.
        /// </summary>
        public static string Summary_Autonomic {
            get {
                return ResourceManager.GetString("Summary_Autonomic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Summary_L {
            get {
                return ResourceManager.GetString("Summary_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical.
        /// </summary>
        public static string Summary_Physical {
            get {
                return ResourceManager.GetString("Summary_Physical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string Summary_R {
            get {
                return ResourceManager.GetString("Summary_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Options.
        /// </summary>
        public static string SummaryImages_AdministratorOptions {
            get {
                return ResourceManager.GetString("SummaryImages_AdministratorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomic Left.
        /// </summary>
        public static string SummaryImages_AutonomicLeft {
            get {
                return ResourceManager.GetString("SummaryImages_AutonomicLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomic Right.
        /// </summary>
        public static string SummaryImages_AutonomicRight {
            get {
                return ResourceManager.GetString("SummaryImages_AutonomicRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black and White Biofield Images.
        /// </summary>
        public static string SummaryImages_BlackAndWhite {
            get {
                return ResourceManager.GetString("SummaryImages_BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Biofield Images.
        /// </summary>
        public static string SummaryImages_ColorBiofield {
            get {
                return ResourceManager.GetString("SummaryImages_ColorBiofield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Left.
        /// </summary>
        public static string SummaryImages_PhysicalLeft {
            get {
                return ResourceManager.GetString("SummaryImages_PhysicalLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Right.
        /// </summary>
        public static string SummaryImages_PhysicalRight {
            get {
                return ResourceManager.GetString("SummaryImages_PhysicalRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Treatment_Age {
            get {
                return ResourceManager.GetString("Treatment_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Treatment_DateOfBirth {
            get {
                return ResourceManager.GetString("Treatment_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Treatment_Gender {
            get {
                return ResourceManager.GetString("Treatment_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string Treatment_Name {
            get {
                return ResourceManager.GetString("Treatment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Treatment.
        /// </summary>
        public static string Treatment_Title {
            get {
                return ResourceManager.GetString("Treatment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string Treatment_VisitDate {
            get {
                return ResourceManager.GetString("Treatment_VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Treatments_FirstName {
            get {
                return ResourceManager.GetString("Treatments_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Treatments_LastName {
            get {
                return ResourceManager.GetString("Treatments_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Treatments_Location {
            get {
                return ResourceManager.GetString("Treatments_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Time.
        /// </summary>
        public static string Treatments_Time {
            get {
                return ResourceManager.GetString("Treatments_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Search.
        /// </summary>
        public static string Treatments_Title {
            get {
                return ResourceManager.GetString("Treatments_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Type.
        /// </summary>
        public static string Treatments_Type {
            get {
                return ResourceManager.GetString("Treatments_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Treatments_View {
            get {
                return ResourceManager.GetString("Treatments_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to alcohol being ingested within the last 24 hours, the Hepatic scan results may be slightly elevated..
        /// </summary>
        public static string TreatmentSummaryPartial_Alcohol {
            get {
                return ResourceManager.GetString("TreatmentSummaryPartial_Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to caffeine being ingested within the last 2 hours, the Cardiovascular and Gastrointestinal scan results may be slightly elevated..
        /// </summary>
        public static string TreatmentSummaryPartial_Caffeine {
            get {
                return ResourceManager.GetString("TreatmentSummaryPartial_Caffeine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to caffeine and wheat being ingested within the last 2 hours, the Cardiovascular and Gastrointestinal scan results may be slightly elevated..
        /// </summary>
        public static string TreatmentSummaryPartial_CaffeineAndWheat {
            get {
                return ResourceManager.GetString("TreatmentSummaryPartial_CaffeineAndWheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to wheat being ingested within the last 2 hours, the Cardiovascular and Gastrointestinal scan results may be slightly elevated..
        /// </summary>
        public static string TreatmentSummaryPartial_Wheat {
            get {
                return ResourceManager.GetString("TreatmentSummaryPartial_Wheat", resourceCulture);
            }
        }
    }
}
