//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EPICCentral.Resources.Views.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Add_Administration {
            get {
                return ResourceManager.GetString("Add_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Add_EmailAddress {
            get {
                return ResourceManager.GetString("Add_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Add_FirstName {
            get {
                return ResourceManager.GetString("Add_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Add_LastName {
            get {
                return ResourceManager.GetString("Add_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Add_Locations {
            get {
                return ResourceManager.GetString("Add_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Add_Organization {
            get {
                return ResourceManager.GetString("Add_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Add_Pin {
            get {
                return ResourceManager.GetString("Add_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Add_Role {
            get {
                return ResourceManager.GetString("Add_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string Add_Title {
            get {
                return ResourceManager.GetString("Add_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user account has been created by an EPIC Central administrator. Please click the link below to complete the registration process:.
        /// </summary>
        public static string AddEmailPartial_AccountCreated {
            get {
                return ResourceManager.GetString("AddEmailPartial_AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Registration.
        /// </summary>
        public static string AddEmailPartial_CompleteRegistration {
            get {
                return ResourceManager.GetString("AddEmailPartial_CompleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},.
        /// </summary>
        public static string AddEmailPartial_Greeting {
            get {
                return ResourceManager.GetString("AddEmailPartial_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to set your username and password. Once you have completed registration, you will be able to log in..
        /// </summary>
        public static string AddEmailPartial_Instructions {
            get {
                return ResourceManager.GetString("AddEmailPartial_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string AddEmailPartial_Salutation {
            get {
                return ResourceManager.GetString("AddEmailPartial_Salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EPIC Central Team.
        /// </summary>
        public static string AddEmailPartial_SalutationName {
            get {
                return ResourceManager.GetString("AddEmailPartial_SalutationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPIC Central: User Registration Email.
        /// </summary>
        public static string AddEmailPartial_Title {
            get {
                return ResourceManager.GetString("AddEmailPartial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active?.
        /// </summary>
        public static string Edit_Active {
            get {
                return ResourceManager.GetString("Edit_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow All.
        /// </summary>
        public static string Edit_AllowAll {
            get {
                return ResourceManager.GetString("Edit_AllowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disallow All.
        /// </summary>
        public static string Edit_DisallowAll {
            get {
                return ResourceManager.GetString("Edit_DisallowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Edit_EmailAddress {
            get {
                return ResourceManager.GetString("Edit_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Edit_FirstName {
            get {
                return ResourceManager.GetString("Edit_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Edit_LastName {
            get {
                return ResourceManager.GetString("Edit_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Edit_Locations {
            get {
                return ResourceManager.GetString("Edit_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of # selected.
        /// </summary>
        public static string Edit_NumberSelected {
            get {
                return ResourceManager.GetString("Edit_NumberSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Edit_Role {
            get {
                return ResourceManager.GetString("Edit_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location(s).
        /// </summary>
        public static string Edit_SelectLocations {
            get {
                return ResourceManager.GetString("Edit_SelectLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user&apos;s role.
        /// </summary>
        public static string Edit_SelectRole {
            get {
                return ResourceManager.GetString("Edit_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string Edit_Title {
            get {
                return ResourceManager.GetString("Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string Edit_UserInformation {
            get {
                return ResourceManager.GetString("Edit_UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Edit_Username {
            get {
                return ResourceManager.GetString("Edit_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically detect timezone when I sign on from a different location..
        /// </summary>
        public static string EditMe_AutomaticallyDetect {
            get {
                return ResourceManager.GetString("EditMe_AutomaticallyDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string EditMe_Cancel {
            get {
                return ResourceManager.GetString("EditMe_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EditMe_EmailAddress {
            get {
                return ResourceManager.GetString("EditMe_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save your user information, please correct the errors below..
        /// </summary>
        public static string EditMe_Errors {
            get {
                return ResourceManager.GetString("EditMe_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string EditMe_FirstName {
            get {
                return ResourceManager.GetString("EditMe_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string EditMe_Language {
            get {
                return ResourceManager.GetString("EditMe_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string EditMe_LastName {
            get {
                return ResourceManager.GetString("EditMe_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/Timezone.
        /// </summary>
        public static string EditMe_RegionTimezone {
            get {
                return ResourceManager.GetString("EditMe_RegionTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string EditMe_Save {
            get {
                return ResourceManager.GetString("EditMe_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My Account.
        /// </summary>
        public static string EditMe_Title {
            get {
                return ResourceManager.GetString("EditMe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string EditMe_UserInformation {
            get {
                return ResourceManager.GetString("EditMe_UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string EditMe_Username {
            get {
                return ResourceManager.GetString("EditMe_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string EditMe_UserSettings {
            get {
                return ResourceManager.GetString("EditMe_UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string List_AddUser {
            get {
                return ResourceManager.GetString("List_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string List_Edit {
            get {
                return ResourceManager.GetString("List_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string List_EditUser {
            get {
                return ResourceManager.GetString("List_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address.
        /// </summary>
        public static string List_EmailAddress {
            get {
                return ResourceManager.GetString("List_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string List_FirstName {
            get {
                return ResourceManager.GetString("List_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string List_LastName {
            get {
                return ResourceManager.GetString("List_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string List_Locations {
            get {
                return ResourceManager.GetString("List_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string List_Organization {
            get {
                return ResourceManager.GetString("List_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string List_UserDetails {
            get {
                return ResourceManager.GetString("List_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string List_Username {
            get {
                return ResourceManager.GetString("List_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string List_View {
            get {
                return ResourceManager.GetString("List_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string View_ChangePassword {
            get {
                return ResourceManager.GetString("View_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string View_Created {
            get {
                return ResourceManager.GetString("View_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string View_Edit {
            get {
                return ResourceManager.GetString("View_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string View_EmailAddress {
            get {
                return ResourceManager.GetString("View_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string View_FirstName {
            get {
                return ResourceManager.GetString("View_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string View_Language {
            get {
                return ResourceManager.GetString("View_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity.
        /// </summary>
        public static string View_LastActivity {
            get {
                return ResourceManager.GetString("View_LastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last lockout.
        /// </summary>
        public static string View_LastLockout {
            get {
                return ResourceManager.GetString("View_LastLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string View_LastName {
            get {
                return ResourceManager.GetString("View_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string View_Locations {
            get {
                return ResourceManager.GetString("View_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in.
        /// </summary>
        public static string View_LoggedIn {
            get {
                return ResourceManager.GetString("View_LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string View_Organization {
            get {
                return ResourceManager.GetString("View_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string View_PasswordChanged {
            get {
                return ResourceManager.GetString("View_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string View_Region {
            get {
                return ResourceManager.GetString("View_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration pending ....
        /// </summary>
        public static string View_RegistrationPending {
            get {
                return ResourceManager.GetString("View_RegistrationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Email.
        /// </summary>
        public static string View_ResendEmail {
            get {
                return ResourceManager.GetString("View_ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string View_Role {
            get {
                return ResourceManager.GetString("View_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} User.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string View_UserInformation {
            get {
                return ResourceManager.GetString("View_UserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string View_Username {
            get {
                return ResourceManager.GetString("View_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string View_UserSettings {
            get {
                return ResourceManager.GetString("View_UserSettings", resourceCulture);
            }
        }
    }
}
